<template>
  <div class="adduser-container">
    <v-container fluid fill-height>
      <v-sheet color="white" elevation="1" class="container ticket-sheet rounded-lg" align="center">

        <h1 class="mb-5">Ajouter un client</h1>
        <v-form ref="form" class="mt-5 mx-5 signup-form" @submit.prevent="validate">
          <v-row>
            <v-col cols="12" md="12">
              <v-text-field type="text" v-model="clientData.company" label="Entreprise" dense></v-text-field>
            </v-col>

            <v-col cols="12" md="6">
              <v-text-field type="text" v-model="clientData.name" label="Prénom" :rules="[rules.required]" dense></v-text-field>
            </v-col>
            <v-col cols="12" md="6">
              <v-text-field type="text" v-model="clientData.surname" label="Nom" :rules="[rules.required]" dense></v-text-field>
            </v-col>
            <v-col cols="12" md="12">
              <v-text-field type="text" v-model="clientData.address.address1" label="Adresse 1" dense></v-text-field>
            </v-col>

            <v-col cols="12" md="12">
              <v-text-field type="text" v-model="clientData.address.address2" label="Adresse 2" dense></v-text-field>
            </v-col>

            <v-col cols="12" md="12">
              <v-text-field type="tel" v-model="clientData.mobile" label="Téléphone mobile" dense></v-text-field>
            </v-col>

            <v-col cols="12" md="12">
              <v-text-field type="tel" v-model="clientData.fixe" label="Téléphone fixe" dense></v-text-field>
            </v-col>

            <v-col cols="12" md="4">
              <v-text-field type="tel" v-model="clientData.address.npa" label="NPA" dense counter maxlength="4"></v-text-field>
            </v-col>
            <v-col cols="12" md="8">
              <v-text-field type="text" v-model="clientData.address.locality" label="Localité" dense></v-text-field>
            </v-col>
            <v-col cols="12" md="12">
              <v-text-field type="email" v-model="clientData.email" label="email" dense></v-text-field>
            </v-col>
          </v-row>
          <v-btn large color="green" :loading="loading" dark depressed @click="validate" class="mt-5"><span class="font-weight-bold">ajouter client</span> </v-btn>
          <p class="feedback">
            {{this.feedback}}
          </p>
        </v-form>
      </v-sheet>
    </v-container>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'
import db from '../../firebase/api'
import algolia from '../../algolia/clientsIndices'
import firebase from 'firebase'
import RemoveNullData from '../../util/removeNullData'
import { ticketDataUserCreatedInterface } from 'types/types'

export default Vue.extend({
  name: 'addUser',
  data () {
    return {
      clientData: {
        company: null,
        name: null,
        surname: null,
        address: {
          address1: null,
          address2: null,
          npa: null,
          locality: null
        },
        mobile: null,
        fixe: null,
        created: null || {} as ticketDataUserCreatedInterface,
        email: null
      },
      loading: false,
      feedback: null || '',
      rules: {
        required: (value:string) => !!value || 'Champ obligatoire'
      }
    }
  },
  methods: {
    async validate () {
      (this.$refs.form as Vue & { validate: () => boolean }).validate() // js version -> this.$refs.form.validate()
      if (!this.clientData.name || !this.clientData.surname) {
        this.feedback = 'Les champs nom et prénom doivent être remplis'
      } else {
        this.feedback = ''

        this.clientData.created.at = firebase.firestore.FieldValue.serverTimestamp()

        // This removes null data recursivly from javascript objects
        const dataWithoutNull:any = RemoveNullData(this.clientData)

        try {
          this.loading = true
          const newUser = await db.collection('clients').doc()
          await newUser.set(dataWithoutNull)

          const statsRef = db.collection('stats').doc('stats')
          await statsRef.update({
            'total-clients': firebase.firestore.FieldValue.increment(1)
          })

          // Fetch Id generated by firebase and assign the id to the object and will be used for algolia
          dataWithoutNull.objectID = newUser.id

          await algolia.saveObjects([dataWithoutNull])
          this.loading = false
          this.$router.push({ name: 'users' })
        } catch (err) {
          this.loading = false
          console.log(err)
        }
      }
    }
  }
})
</script>

<style>
.adduser-container .feedback {
  color: red;
  margin-top: 2em;
  margin-bottom: 0;
}
</style>
